services:
    kakaku:
        build:
            context: https://github.com/gkjg8787/kakakuscraping-fastapi.git
        ports:
            - "8000:8000"
        init: true
        volumes:
            - ./kakaku/settings.py:/app/kakaku/settings.py
            - ./data/kakaku/db:/app/db
            - ./data/kakaku/log:/app/log
    search2kakaku:
        build:
            context: https://github.com/gkjg8787/search2kakaku.git
        init: true
        ports:
            - "8120:8120"
        depends_on:
            - search
        volumes:
            - ./search2kakaku/settings.py:/app/search2kakaku/settings.py
            - ./data/search2kakaku/db:/app/db
            - ./data/search2kakaku/log:/app/log
    search:
        build:
            context: https://github.com/gkjg8787/external_search.git
        ports:
            - "8060:8060"
        env_file:
            - ./search/.env
        volumes:
            - ./search/settings.py:/app/ex_search/settings.py
            - ./data/search/db:/app/db
            - ./data/search/log:/app/log
            - ./data/search/cookies:/app/cookies
        depends_on:
            - nodriver_api
    redis:
        image: redis:latest
        container_name: redis_broker
        ports:
            - "6379:6379"
    celery_worker:
        build:
            context: https://github.com/gkjg8787/search2kakaku.git
        container_name: celery_worker
        command: celery -A tasks worker --loglevel=info --concurrency=1
        volumes:
            - ./search2kakaku/settings.py:/app/search2kakaku/settings.py
            - ./data/search2kakaku/db:/app/db
            - ./data/search2kakaku/log:/app/log
        depends_on:
            - search
            - redis
    celery_beat:
        build:
            context: https://github.com/gkjg8787/search2kakaku.git
        container_name: celery_beat
        command: celery -A tasks beat --loglevel=info
        volumes:
            - ./search2kakaku/settings.py:/app/search2kakaku/settings.py
            - ./data/search2kakaku/db:/app/db
            - ./data/search2kakaku/log:/app/log
        depends_on:
            - search
            - redis
    search_gui:
        build:
            context: https://github.com/gkjg8787/external_search_gui.git
        ports:
            - "8110:8110"
        depends_on:
            - search
        volumes:
            - ./search_gui/settings.py:/app/ex_search_gui/settings.py
            - ./data/search_gui/db:/app/db
            - ./data/search_gui/log:/app/log
    nodriver_api:
        build:
            context: https://github.com/gkjg8787/search_query_analysis.git
        init: true
        ports:
            - "8090:8090"
        shm_size: "2gb"
        command : uvicorn main:app --host 0.0.0.0 --port 8090
        volumes:
            - ./data/nodriver_api/cookie:/app/cookie
    